### ISSUE TITLE
Does it make sense for this lib to support emscripten?

### ISSUE THREAD

**Issue by svenstaro** [dcuddeback/termios-rs#13]
I was just wondering whether it made sense for you to support emscripten/wasm32 or whether you think that this makes no sense at all.

**Comment by dcuddeback** [comment]
@svenstaro That doesn't make much sense to me. Termios is a POSIX API supported by most Unix operating systems. Without an OS-supplied termios API, there would be nothing for this library to provide bindings for. It's the same reason this library doesn't support Windows.
