### ISSUE TITLE
Doesn't compile on Android

### ISSUE THREAD

**Issue by YtvwlD** [dcuddeback/termios-rs#17]
I'm trying to get bat to run on my smartphone. But the build fails at termios with a very weird error message - `E0433: could not find target in os`.

I figured that it's that way because `target_os = "android"`, not `target_os = "linux"`.

I think one could simple re-use the Linux definitions, but I'm not entirely sure.

**Comment by dcuddeback** [comment]
@YtvwlD See #15 for a patch that's supposed to fix this. I can merge #15 as long as I can QA it, but I'm not familiar with Android. If you have a procedure I can follow to test this, please feel free to add that as a comment on #15.

**Comment by dcuddeback** [comment]
Fixed in #19.
