### ISSUE TITLE
Constants for powerpc on linux are incorrect

### ISSUE THREAD

**Issue by raphaelcohn** [dcuddeback/termios-rs#20]
See the values in musl (<https://github.com/bminor/musl/blob/05ac345f895098657cf44d419b5d572161ebaf43/arch/powerpc64/bits/termios.h>), say, for baud rates and C-control mode flags.

**Comment by dcuddeback** [comment]
Nobody's worked on PowerPC. The platforms that have been tested are listed in the README: https://github.com/dcuddeback/termios-rs#dependencies.

Feel free to send a patch.

**Comment by raphaelcohn** [comment]
Closing as gone stale.
